-- 코드를 입력하세요
SELECT o.ANIMAL_ID, o.ANIMAL_TYPE, o.NAME
FROM ANIMAL_OUTS o
JOIN (SELECT ANIMAL_ID
     FROM ANIMAL_INS
     WHERE SEX_UPON_INTAKE LIKE 'Intact%'
     ) i ON i.ANIMAL_ID=o.ANIMAL_ID
WHERE o.SEX_UPON_OUTCOME LIKE 'Spayed%' OR o.SEX_UPON_OUTCOME LIKE 'Neutered%'
ORDER BY o.ANIMAL_ID