-- 코드를 작성해주세요
SELECT  SUM(SCORE) SCORE, he.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_GRADE hg
JOIN HR_EMPLOYEES he ON hg.EMP_no=he.EMP_NO
JOIN HR_DEPARTMENT hd ON hd.DEPT_ID=he.DEPT_ID
WHERE hg.YEAR=2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1