-- 코드를 작성해주세요
SELECT c.ITEM_ID, c.ITEM_NAME, c.RARITY
FROM    ITEM_INFO AS p
JOIN    ITEM_TREE  AS t ON t.PARENT_ITEM_ID = p.ITEM_ID
JOIN    ITEM_INFO AS c ON c.ITEM_ID = t.ITEM_ID
WHERE   p.RARITY = 'RARE'
ORDER BY c.ITEM_ID DESC;