-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES s ON b.BOOK_ID=s.BOOK_ID
WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE<'2022-02-01'
GROUP BY CATEGORY
ORDER BY CATEGORY