-- 코드를 작성해주세요
SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i
JOIN ITEM_TREE t ON i.ITEM_ID=t.ITEM_id
WHERE NOT EXISTS(
SELECT 1
FROM ITEM_TREE ex
WHERE ex.PARENT_ITEM_ID=i.ITEM_ID
)
ORDER BY ITEM_ID DESC