-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT f.ID, n.FISH_NAME, f.LENGTH,
    RANK() OVER (PARTITION BY f.FISH_TYPE ORDER BY f.LENGTH DESC) AS rnk
    FROM FISH_INFO f
    JOIN FISH_NAME_INFO n ON f.FISH_TYPE = n.FISH_TYPE
) j
WHERE rnk = 1
ORDER BY ID;