-- 코드를 입력하세요
SELECT
EXTRACT(YEAR FROM SALES_DATE) YEAR,
EXTRACT(MONTH FROM SALES_DATE) MONTH,
GENDER,
COUNT(DISTINCT s.USER_ID) USERS
FROM USER_INFO i
JOIN ONLINE_SALE s ON i.USER_ID=s.USER_ID
WHERE GENDER IS NOT  NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER