-- 코드를 입력하세요
SELECT DISTINCT c.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID=c.CAR_ID
WHERE c.CAR_TYPE='세단'
AND MONTH(h.START_DATE)='10'
ORDER BY CAR_ID DESC