-- 코드를 작성해주세요
SELECT CHILD.ITEM_ID, CHILD.ITEM_NAME, CHILD.RARITY
FROM ITEM_INFO AS PARENT
JOIN ITEM_TREE IT
ON IT.PARENT_ITEM_ID=PARENT.ITEM_ID
AND PARENT.RARITY='RARE'
JOIN ITEM_INFO AS CHILD ON IT.ITEM_ID=CHILD.ITEM_ID
ORDER BY CHILD.ITEM_ID DESC;