-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', f.BOARD_ID,'/', FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE f
JOIN (SELECT BOARD_ID 
     FROM USED_GOODS_BOARD b
     ORDER BY VIEWS DESC
     LIMIT 1) b ON b.BOARD_ID=f.BOARD_ID
     ORDER BY FILE_ID DESC