-- 코드를 작성해주세요
SELECT COUNT(*) FISH_COUNT, MAX(ORIGIN_LENGTH) MAX_LENGTH, FISH_TYPE
FROM (SELECT CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END CALCULATED_LENGTH, FISH_TYPE, LENGTH ORIGIN_LENGTH
FROM FISH_INFO) i
GROUP BY FISH_TYPE
HAVING AVG(CALCULATED_LENGTH)>=33
ORDER BY FISH_TYPE