-- 코드를 작성해주세요
SELECT 
E.EMP_NO,
E.EMP_NAME,
CASE 
WHEN G.AVG_SCORE >= 96 THEN 'S'
WHEN G.AVG_SCORE >= 90 THEN 'A'
WHEN G.AVG_SCORE >= 80 THEN 'B'
ELSE 'C'
END AS GRADE,
CASE 
WHEN G.AVG_SCORE >= 96 THEN E.SAL * 0.2
WHEN G.AVG_SCORE >= 90 THEN E.SAL * 0.15
WHEN G.AVG_SCORE >= 80 THEN E.SAL * 0.1
ELSE 0
END BONUS
FROM (
    SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) G
JOIN HR_EMPLOYEES E ON E.EMP_NO = G.EMP_NO
ORDER BY E.EMP_NO;