-- 코드를 입력하세요
SELECT ri.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO ri
JOIN (
SELECT FOOD_TYPE, MAX(FAVORITES) MAXIMUM
FROM REST_INFO
GROUP BY FOOD_TYPE
) m ON ri.FOOD_TYPE=m.FOOD_TYPE AND ri.FAVORITES=m.MAXIMUM
ORDER BY FOOD_TYPE DESC