-- 코드를 입력하세요
SELECT p.CATEGORY, p.PRICE MAX_PRICE, p.PRODUCT_NAME
FROM FOOD_PRODUCT p
JOIN (
    SELECT CATEGORY, MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) j ON p.CATEGORY=j.CATEGORY AND p.PRICE=j.MAX_PRICE
ORDER BY p.PRICE DESC